### ISSUE TITLE
Copy files from composer/composer repo 1:1

### ISSUE THREAD

**Issue by alcohol** [composer/xdebug-handler#1]
Copy all the relevant files from the [`composer/composer`](/composer/composer) repository in their current state.

**Comment by johnstevenson** [comment]
If you set me up a skeleton package, with the hooks and a composer.json (namespace `Composer\XdebugHandler`, no requires except phpunit for dev) then I'll add the relevant files, which will obviously need initial modification regarding the namespacing, incorporating the IniHelper etc.

Does this sound like a plan?

**Comment by alcohol** [comment]
Yeah I can invest some time later today. Is that okay with you?

If not, feel free to get started and just open a PR and tag me. We can have some quick discussion there (if necessary).

**Comment by johnstevenson** [comment]
What's the best repo procedure here (and have I got push access)? For `windows-setup` I have a local clone only, and push from there (presumably because the repo was transferred from my account).

**Comment by alcohol** [comment]
You have push access. But PR's is probably the nicest flow.

**Comment by alcohol** [comment]
You can just use:

```
git clone git@github.com:composer/xdebug-handler
```

**Comment by johnstevenson** [comment]
I'm not wildly bothered about push access and would prefer to PR stuff (but how does that work from a directly cloned repo? Or is a clone of a fork better?)

**Comment by alcohol** [comment]
Use branches. Or fork. Whichever you prefer.

**Comment by alcohol** [comment]
I think I forked most composer repositories. But in the docker repo I usually just work on it directly. Doesn't see a lot of activity though so that is why mostly.
