### ISSUE TITLE
Fix color output handling

### ISSUE THREAD

**Issue by johnstevenson** [composer/xdebug-handler#10]
XdebugHandler only recognizes `--ansi` and `--no-ansi` command-line options, so we need to incorporate some of the other commonly used options:

 `--color`, `--colors`, `--color=...`, `--colors=...`

I'll keep the changes small and simple.

**Comment by alcohol** [comment]
What do we actually have as output? Should there be any?

**Comment by johnstevenson** [comment]
We don't, but restarting results in piped `STDOUT`, so we force color output with the `--ansi` flag (if we are terminal).

**Comment by alcohol** [comment]
Hmm. That seems more specific to `composer` though, and not so much this package. Would it perhaps be an idea to allow the 'end user' to specify some sort of handler (callback) for how to handle restarting?

**Comment by johnstevenson** [comment]
I think this is a general issue, because the user will get color output if xdebug is not loaded (or allowed through `WHATEVER_ALLOW_XDEBUG`) but will not if the process is restarted.

I was thinking along the lines of an optional constructor param: `$colorOption = ''`, which is the flag used by the app to force color output (`--ansi` for Composer).

If it is empty we ignore it, otherwise if neither it nor its negated value is in the command-line args, we add it (which is what we do at the moment).

The negated values, `--no-ansi --no-color(s) --color(s)=never` could be ascertained from `$colorOption`

**Comment by alcohol** [comment]
Alright :-)

**Comment by alcohol** [comment]
Is this now resolved by your merged PR?

**Comment by johnstevenson** [comment]
Indeed it is
