### ISSUE TITLE
Usage as a standalone binary

### ISSUE THREAD

**Issue by morozov** [composer/xdebug-handler#107]
Would it be possible to implement a standalone binary based on the library that would run an arbitrary PHP application that doesn't have xdebug-handler bundled?

For instance, there's no plan to adapt it by PHPUnit (https://github.com/sebastianbergmann/phpunit/issues/3544). Not having Xdebug loaded may significantly improve test performance, and code coverage may be collected by other means than Xdebug (e.g. PCOV).

**Comment by weirdan** [comment]
Shameless plug: you may want to try https://github.com/weirdan/run-without-xdebug

**Comment by morozov** [comment]
This looks exactly like what I was looking for :blush: Thanks @weirdan!

**Comment by Seldaek** [comment]
Closing here then.
