### ISSUE TITLE
Unable to abort restarted process with Ctrl-C

### ISSUE THREAD

**Issue by weirdan** [composer/xdebug-handler#109]
Version 1.4.2 suppresses the SIGINT signal, and that suppression is inherited by the restarted process. 

The reason for this explained in [POSIX.1](https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html)

> Signals set to the default action (SIG_DFL) in the calling process image shall be set to the default action in the new process image. Except for SIGCHLD, **signals set to be ignored (SIG_IGN) by the calling process image shall be set to be ignored by the new process image**. Signals set to be caught by the calling process image shall be set to the default action in the new process image (see <signal.h>).

So, unless the application restores the signal handler or sets its own you cannot stop it with SIGINT anymore.

_Originally posted by @weirdan in https://github.com/composer/xdebug-handler/pull/108#issuecomment-674467067_

**Reproduce repo**
https://github.com/weirdan/xdebug-handler-unstoppable

**Reproduce steps**
* `git clone git@github.com:weirdan/xdebug-handler-unstoppable`
* `cd xdebug-handler-unstoppable`
* `composer install`
* `php test.php`
* Press Ctrl-C

**Expected result**
The process should be aborted.

**Actual result**
The process is not aborted.

**Additional details**
Downgrading `composer/xdebug-helper` to 1.4.1 fixes the issue.

![image](https://user-images.githubusercontent.com/57403/90325057-62d22000-df7f-11ea-977f-9f7f05094203.png)

**Comment by johnstevenson** [comment]
https://github.com/weirdan/xdebug-handler-unstoppable Is this a private repo?

```
$ git clone git@github.com:weirdan/xdebug-handler-unstoppable
Cloning into 'xdebug-handler-unstoppable'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by weirdan** [comment]
It was, sorry about that. I've just made it public, so please try again.

**Comment by johnstevenson** [comment]
@weirdan Thanks for this.

> So, unless the application restores the signal handler or sets its own you cannot stop it with SIGINT anymore.

Interestingly, calling `pcntl_signal_get_handler(SIGINT)` in the child process returns `SIG_DFL` rather than than the inherited `SIG_IGN` from the parent, although it clearly doesn't behave this way:

https://github.com/php/php-src/blob/8f61854108a916938095eccaad078b9c53078d4d/ext/pcntl/pcntl.c#L973-L977

Hopefully, I should be able to call `pcntl_signal(SIGINT, SIG_DFL)` in the restart to restore the default handler - but only if a handler function has not been set.

**Comment by weirdan** [comment]
Thanks. I can confirm `dev-master` is working as expected for me.

**Comment by weirdan** [comment]
> Interestingly, calling pcntl_signal_get_handler(SIGINT) in the child process returns SIG_DFL rather than than the inherited SIG_IGN from the parent, although it clearly doesn't behave this way:

Reported that: https://bugs.php.net/bug.php?id=79994

**Comment by johnstevenson** [comment]
Thanks for testing. Not sure it is a bug though, instead it looks like intended behaviour in that `php_signal_table` is initiated with null action values (although I haven't stepped through the code to be certain)
