### ISSUE TITLE
Try to support stream_isatty in restarted processes

### ISSUE THREAD

**Issue by Seldaek** [composer/xdebug-handler#112]
See https://github.com/composer/composer/issues/9454#issuecomment-725415393 - it'd be great if we find a way to make this work.

Either with proc_open (maybe works?), or alternatively maybe setting an env var so the restarted process knows it is in a tty even tho stream_isatty is false..

Not super critical, especially with Xdebug 3 being faster and hopefully making this hackery unnecessary.

**Comment by ktomk** [comment]
While we were there, just filed a PR with a first, minimal implementation.

`stream_isatty` verified in example in https://github.com/composer/composer/issues/9454#issuecomment-725434779

**Comment by Seldaek** [comment]
BTW, I just tried Xdebug 3 and while it's faster, it's still not fast enough IMO, probably will need to keep disabling it. I'll create a new issue for this.
