### ISSUE TITLE
Save original xdebug settings

### ISSUE THREAD

**Issue by sidz** [composer/xdebug-handler#119]
It would be great to store somewhere original xdebug parameters.

Q: Why do I need this?
A: Our application works on top of phpunit and we would like to know whether code coverage parameter was enabled after xdebug handler restarted process or not. Mostly it is needed for xdebug 3 and we would like to get at least `xdebug.mode` (for xdebug 3) and `xdebug.coverage_enable` (for xdebug < 3)

There is a workaround:
We may get and parse all ini files through `XdebugHandler::getRestartSettings()['inis']` on our end but it would be good to have this feature in xdebug-handler.

I can spend some time and prepare a pull request if you think that it will be good to have such feature.

**Comment by sidz** [comment]
ping @Seldaek or @johnstevenson

**Comment by johnstevenson** [comment]
Not all xdebug configuration will be found in the ini file, so you may be best [extending](https://github.com/composer/xdebug-handler#extending-the-library) `XdebugHandler` and saving what you want either in the environment or a temp file.

**Comment by sidz** [comment]
thanks. going to close the issue.
