### ISSUE TITLE
Support modern PHP for version 2

### ISSUE THREAD

**Issue by johnstevenson** [composer/xdebug-handler#125]
We could consider dropping support for older PHPs for version 2. Any dependents that support a  PHP version less than whatever we decide our minimum is should be able to require `^1.4 || ^2.0`, so their code will need to work with both versions.

Looking at all the dependents listed on Packagist, the vast majority do not extend the class so this is very simple (see item 1 below) and for those few that do extend the class it shouldn't really be any harder. The BC breaks will be:

1. **Constructor _$colorOption_ optional param dropped:**
Using `new XdebugHandler('myapp')`  would also work for 1.x because proc_open is used (unless only passthru is available). Using `new XdebugHandler('myapp', '--ansi')` would also work for 2.x since the extra param is ignored.

2. **Protected `restart` param _$command_ changed from a string to an array:**
By not typehinting the method it can be used by 1.x and 2.x (unless _$command_ is modified, which would require a little work - although this is not seen in any dependents). 
3. **Protected `requiresRestart` param _$isLoaded_ changed to _$default_:**
By not typehinting the method it can be used by 1.x and 2.x since both are boolean.
4. **The process will not restart if xdebug `mode` is `off`:**
This is not relevant to the code.

@Seldaek Interested in your input here. Perhaps a minimum of `7.1`, although the xdebug mode stuff is only relevant on `7.2` upwards.

**Comment by Seldaek** [comment]
If you feel it brings you much value feel free. I don't mind so much from a Composer perspective as it's used in a very superficial way. 

For Composer 2.2 I'm still pondering whether 7.1 or 7.2 is the right choice, but I suspect it might become 7.2 as the timeline is slipping..

**Comment by johnstevenson** [comment]
>If you feel it brings you much value

By using 7.2.5 (as per Symfony 5) we can remove a few `PHP_VERSION_ID` checks but other than the warm fuzzy feeling you may get by using a few typehints and not having to worry about PHP-5.3.2, probably not that much.

However, it is not a huge amount of work so I'm minded to do it anyway.

**Comment by Seldaek** [comment]
Ok, the only issue is we only ship one phar for all php versions so for Composer it means we stay stuck on v1 for 2.1 and can upgrade to v2 for 2.2 if the php req is compatible. So if the changes are mostly cosmetic I'd say maybe delay this and do a v3 or even bump the php req in a 2.1 so all dependents have a chance to use the 2.0 refactorings and Xdebug 3 handling..

**Comment by johnstevenson** [comment]
Ah, good point. I'll leave it until Composer 2.2 is a thing (or close to a thing). Thanks.

**Comment by johnstevenson** [comment]
Implemented in https://github.com/composer/xdebug-handler/pull/143
