### ISSUE TITLE
How to replace colorOption in 2.0?

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/xdebug-handler#131]
Hi,
I upgraded to version 2.0 and the 2nd constructor parameter vanished. I used to pass `--ansi` in there so that Symfony Console apps could continue to be in color.

What can I do in 2.0 to restore this behaviour? Thanks!

**Comment by weirdan** [comment]
You shouldn't need that option anymore. See #123

**Comment by ondrejmirtes** [comment]
With xdebug-handler 2.0.1:

<img width="739" alt="Screenshot 2021-05-14 at 14 58 52" src="https://user-images.githubusercontent.com/104888/118274054-f7dd5780-b4c4-11eb-934c-c5ccf8ad9148.png">

With xdebug-handler 1.4.6 and passing `--ansi` as the 2nd constructor argument:

<img width="724" alt="Screenshot 2021-05-14 at 15 00 20" src="https://user-images.githubusercontent.com/104888/118274296-3f63e380-b4c5-11eb-85ee-9c9f9e498e10.png">

**Comment by johnstevenson** [comment]
We only needed `$colorOption` when we were using `passthru` (because it uses a pipe for the output which will fail `is_atty` detection), whereas now we use `proc_open` without touching the file descriptors.

https://github.com/composer/xdebug-handler/blob/main/UPGRADE.md

Color support will be detectable in the restarted process. So is that not happening for you?

**Comment by ondrejmirtes** [comment]
Yeah. This is how Symfony detects it (ironically it mentions xdebug-handler in there) so I guess it somehow breaks:

```
    /**
     * Returns true if the stream supports colorization.
     *
     * Colorization is disabled if not supported by the stream:
     *
     * This is tricky on Windows, because Cygwin, Msys2 etc emulate pseudo
     * terminals via named pipes, so we can only check the environment.
     *
     * Reference: Composer\XdebugHandler\Process::supportsColor
     * https://github.com/composer/xdebug-handler
     *
     * @return bool true if the stream supports colorization, false otherwise
     */
    protected function hasColorSupport()
    {
        // Follow https://no-color.org/
        if (isset($_SERVER['NO_COLOR']) || false !== getenv('NO_COLOR')) {
            return false;
        }

        if ('Hyper' === getenv('TERM_PROGRAM')) {
            return true;
        }

        if (\DIRECTORY_SEPARATOR === '\\') {
            return (\function_exists('sapi_windows_vt100_support')
                && @sapi_windows_vt100_support($this->stream))
                || false !== getenv('ANSICON')
                || 'ON' === getenv('ConEmuANSI')
                || 'xterm' === getenv('TERM');
        }

        return stream_isatty($this->stream);
    }
```

**Comment by johnstevenson** [comment]
It works fine with Composer snapshot, which uses (almost) the same code as the latest Symfony Console.

![composer-xdebug-handler](https://user-images.githubusercontent.com/881777/118279716-5c97b280-b4c3-11eb-8c91-4c5cabbc5643.png)

**Comment by ondrejmirtes** [comment]
It now works for me too which is a bit weird. I'll let you know if I can reproduce it again, thanks.

**Comment by johnstevenson** [comment]
The acid test could be running your second example `With xdebug-handler 1.4.6 and passing --ansi as the 2nd constructor argument` without Xdebug already loaded. I'd expect this not to  colourize the output.

Set `XDEBUG_HANDLER_DEBUG=1` to see the xdebug-handler output.
