### ISSUE TITLE
INI file and broken disable_functions

### ISSUE THREAD

**Issue by KapitanOczywisty** [composer/xdebug-handler#132]
I have an issue, when the copied `ini` file have `proc_open` in `disable_functions`, because of broken merging of additional files. This causes composer to stop working.

#### This is simplified reproduction of this issue:
`php.ini` - default from compilation
```ini
disable_functions=proc_open
```
#### And additional ini files
`01-first.ini` - this contains some rules in `[PATH=..]` section
```ini
[PATH=/var/www/html]
memory_limit=512G
```
`02-second.ini` - this contains rules without sections
```ini
disable_functions=""
```

Composer from these files will produce following `ini` file:
```ini
disable_functions=proc_open
[PATH=/var/www/html]
memory_limit=512G
disable_functions=""
```

As you can see `disable_functions=""` is no longer applicable to all scripts but only to `/var/www/html`. In addition to this also all composer settings are ignored as well, since these are *in* `PATH` section.

**Comment by johnstevenson** [comment]
I'm not sure what your setup is, or its intention, but running a cli script without proc_open is never a good idea.

Perhaps you could run Composer with `XDEBUG_HANDLER_DEBUG=1` and show the output.

**Comment by KapitanOczywisty** [comment]
My ini configuration have empty `disable_functions`, but this is set in additional ini file, and with the way this library is merging ini files, this setting is ending up after `[PATH=...]`, which causes php to use default value from original/main ini file.

https://github.com/composer/xdebug-handler/blob/964adcdd3a28bf9ed5d9ac6450064e0d71ed7496/src/XdebugHandler.php#L382-L389
In this part of the code there should be an additional step to remove everything after any `[PATH=...]` or `[HOST=...]`, since these are totally ignored in cli. (php-src reference at the end)

---


One more time, what the issue is. With these files loaded:
`php.ini`
```ini
disable_functions=proc_open
```
`01-first.ini`
```ini
[PATH=/var/www/html]
memory_limit=512G
```
`02-second.ini`
```ini
disable_functions=""
```
Everything should be merged as:
```ini
; php.ini
disable_functions=proc_open

; 01-first.ini
; [PATH=...] section removed

; 02-second.ini
disable_functions=""
```

### PHP-src reference

https://github.com/php/php-src/blob/master/main/php_ini.c#L247-L308

In this code you can see that after first `HOST/PATH` section everything is stored in the separate `hashtable`, and other sections are not reverting to global `hashtable` (L278 key is null). [Hashtable is only reseted after whole file](https://grep.app/search?q=RESET_ACTIVE_INI_HASH%28%29&filter[repo][0]=php/php-src) Also as we can read in [php manual](https://www.php.net/manual/en/ini.sections.php), these sections are only used with cgi.

Thus, It's safe to ignore everything after `[PATH=...]` and `[HOST=...]` in each ini file.

**Comment by johnstevenson** [comment]
Okay,I've got it now. It would have been helpful, to me anyway, if you had explained that we weren't following the `[PATH=]` and `[HOST=]` section rules (which I hadn't considered before), but you've more than made up for it with your detailed information! So many thanks.

I'll fix this.

**Comment by KapitanOczywisty** [comment]
It was obvious to me :) Sorry for my chaotic report, but I'm glad that we're on the same page now. Let me know if you need any additional feedback.

**Comment by johnstevenson** [comment]
No worries. If you could cast your eye over the PR it would be good.
