### ISSUE TITLE
Possible performance issue with version 2.0.4

### ISSUE THREAD

**Issue by pacproduct** [composer/xdebug-handler#146]
Hi :)

We're using `FriendsOfPHP/PHP-CS-Fixer` version `3.0.4` which relies on this package `composer/xdebug-handler` in version 2.

Since the recent upgrade from `xdebug-handler` version `2.0.3` to `2.0.4`, `PHP-CS-Fixer` seems to be suffering from an important performance drop.

More details and procedure to reproduce the issue on the ticket I opened on their repository: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6310

**Comment by johnstevenson** [comment]
Have you run it with `XDEBUG_HANDLER_DEBUG=1`, as per https://github.com/composer/xdebug-handler#troubleshooting

It might help to troubleshoot things.

**Comment by pacproduct** [comment]
@johnstevenson I just did, here are results:

- With `xdebug-handler` 2.0.4 :
  ```shell
	hydrop@8c4678f103e8:/tmp/demo$ XDEBUG_HANDLER_DEBUG=1 tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src
	xdebug-handler[632] Checking PHP_CS_FIXER_ALLOW_XDEBUG
	xdebug-handler[632] The Xdebug extension is loaded (2.7.0RC2)
	xdebug-handler[632] No restart (PHP_CS_FIXER_ALLOW_XDEBUG=) Allowed by application
	Loaded config default from "/tmp/demo/.php-cs-fixer.dist.php".
	Paths from configuration file have been overridden by paths provided as command arguments.

	Fixed all files in 18.148 seconds, 6.000 MB memory used
  ```
- With `xdebug-handler` 2.0.3 :
  ```shell
	hydrop@8c4678f103e8:/tmp/demo$ XDEBUG_HANDLER_DEBUG=1 tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src
	xdebug-handler[670] Checking PHP_CS_FIXER_ALLOW_XDEBUG
	xdebug-handler[670] The Xdebug extension is loaded (2.7.0RC2)
	xdebug-handler[670] Process restarting (PHP_CS_FIXER_ALLOW_XDEBUG=internal|2.7.0RC2|1|*|*)
	xdebug-handler[670] Running /usr/bin/php7.3 -n -c /tmp/7VvtyF tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src
	xdebug-handler[672] Checking PHP_CS_FIXER_ALLOW_XDEBUG
	xdebug-handler[672] Restarted (37 ms). The Xdebug extension is not loaded
	Loaded config default from "/tmp/demo/.php-cs-fixer.dist.php".
	Paths from configuration file have been overridden by paths provided as command arguments.

	Fixed all files in 0.954 seconds, 14.000 MB memory used
	xdebug-handler[670] Restarted process exited 0
  ```

**Comment by SpacePossum** [comment]
>   xdebug-handler[632] No restart (PHP_CS_FIXER_ALLOW_XDEBUG=) Allowed by application

hmm do we have to set `PHP_CS_FIXER_ALLOW_XDEBUG` in the application itself somewhere?

**Comment by johnstevenson** [comment]
Yup it's a bug. You can get around it by running a version of xdebug 3 until I've fixed this.

**Comment by johnstevenson** [comment]
Fixed in releases  [2.0.5](https://github.com/composer/xdebug-handler/releases/tag/2.0.5) and  [3.0.2](https://github.com/composer/xdebug-handler/releases/tag/3.0.2). Thanks for the catch.

**Comment by SpacePossum** [comment]
thanks @johnstevenson !

**Comment by pacproduct** [comment]
@johnstevenson I can confirm version `2.0.5` does fix our issue. Many thanks for the prompt fix! :) :+1:
