### ISSUE TITLE
Robustness of the persistent option

### ISSUE THREAD

**Issue by lstrojny** [composer/xdebug-handler#150]
When the persistent mode is used but `PHP_INI_SCAN_DIR` is ignored by the target binary, xdebug-handler will not notice that it didn't succeed. I am wondering if xdebug-handler should somehow detect that there was a problem.

See https://github.com/NixOS/nixpkgs/pull/221845 for a case where that happened because of the specific way nix packages PHP.

**Comment by johnstevenson** [comment]
Why does the binary ignore `PHP_INI_SCAN_DIR`?

**Comment by lstrojny** [comment]
@johnstevenson frankly, it looks like a bug to me. That’s also why the issue here is more of a question than an actual issue report. I was wondering if xdebug-handler should be hardened to detect such an environment.
