### ISSUE TITLE
BadBadBut

### ISSUE THREAD

**Issue by Seldaek** [composer/xdebug-handler#154]
I'm guessing you may have seen this already but anyway I figured I'd ask, do you think that https://github.com/composer/xdebug-handler/blob/main/src/Process.php#L35 is enough to cover it?

References:

- https://flatt.tech/research/posts/batbadbut-you-cant-securely-execute-commands-on-windows/
- https://twitter.com/nicolasgrekas/status/1777949725502668841

**Comment by johnstevenson** [comment]
Yes, we quote everything safely. Our implementation is taken from https://github.com/johnstevenson/winbox-args which has a comprehensive test suite.

And from PHP7.4 we take advantage of `proc_open` directly calling a program without going through the shell. So on Windows,  cmd.exe is not used and in our case createProcess calls the PHP binary directly (with PHP taking care of escaping the arguments).

**Comment by Seldaek** [comment]
Ok sounds good.
