### ISSUE TITLE
add cli-command to auto-restart other applications

### ISSUE THREAD

**Issue by staabm** [composer/xdebug-handler#157]
at PHPStan we have a `--debug` switch which utilizes xdebug-handler PHP APIs to enable/disable xdebug restarts.
we have a similar implementation in rector.

I am also running php-code-sniffer sometimes and realized it is slower when xdebug is running.
adding the same logic we already have in PHPStan and rector to also php-code-sniffer is hard todo because it would require a lot of testing and adds complexity which I am sure they don't want (which totally makes sense).

this made me think, whether it would make sense if this `xdebug-handler` package could provide a cli command, which I can just wrap any other cli command in and add said xdebug restart handling.
in case of codesniffer this would e.g. look like
`xdebug-handler --restart-if-loaded vendor/bin/phpcs`

that way I could plug this behaviour to any php cli application

**Comment by weirdan** [comment]
Perhaps you'll find https://github.com/weirdan/run-without-xdebug useful, it does just that.

**Comment by staabm** [comment]
nice. thank you for pointing me to it.

still I wonder whether it would be a perfect fit for this lib here.

**Comment by johnstevenson** [comment]
You can always use an environment variable to limit the Xdebug overhead:

```
XDEBUG_MODE=off ...
```

xdebug-handler doesn't bother to restart if this is set, because the overhead is minimal.

**Comment by staabm** [comment]
awesome, thank you both
