### ISSUE TITLE
Blocking 1.0 release

### ISSUE THREAD

**Issue by felixfbecker** [composer/xdebug-handler#17]
It would be nice to have a list of what's blocking 1.0 release to contribute and have a rough ETA for adoption. Feel free to edit this issue or create milestone

**Comment by webflo** [comment]
Would like to use it in https://github.com/drush-ops/drush-launcher/pull/41

**Comment by AJenbo** [comment]
Any progress on this? Looks like the churn on the code has slowed down.

**Comment by johnstevenson** [comment]
Sorry guys, but (free-) time is hard to plan, as you know. Anyway, here is what I think needs to be sorted prior to a full release:

- [ ] Output reporting, as per post-merge comments on https://github.com/composer/xdebug-handler/pull/28. @felixfbecker Are you happy with the `$xdebug->setLogger()` proposal?

- [ ] An itch I need to scratch, regarding the handling of _any_ possible command-line ini settings, as descibed in https://github.com/composer/xdebug-handler/issues/29

Consensus on these and we should be good to go.

**Comment by felixfbecker** [comment]
100% happy with implementing `Psr\Log\LoggerAwareInterface`. Although the constructor might also want to accept a logger.

**Comment by johnstevenson** [comment]
Thanks @felixfbecker. I stayed away from adding the logger to the constructor because it is optional (yup, so is the $colorOption) but mainly because calling `setLogger(null)` disables any output - even if the user has added a `-vvv` param.

The alternative (using the constructor) would be to _require_ a null logger to achieve this functionality, which seems like overkill. Anyway, I'll PR it and folks can make their mind up.

**Comment by johnstevenson** [comment]
Just one item left now: [Allow output to be logged or disabled #31](https://github.com/composer/xdebug-handler/pull/31).

**Comment by weitzman** [comment]
Looks like the last blocker has been merged. Woo hoo!

**Comment by AJenbo** [comment]
It's still in review

**Comment by felixfbecker** [comment]
Anything missing?

**Comment by johnstevenson** [comment]
I think that's it now. @Seldaek Are you happy to release this?

**Comment by felixfbecker** [comment]
:shipit:

**Comment by Seldaek** [comment]
No problem for me if you're happy with it :) I haven't followed very closely tbh, but anyway if there's a problem we can always make another release, so yes I'd say let's go for it.

**Comment by felixfbecker** [comment]
Let's do it

**Comment by johnstevenson** [comment]
Sure, but it will have to wait until tomorrow. It's beer o'clock in the UK now!

**Comment by johnstevenson** [comment]
1.0.0 finally released. Enjoy.

**Comment by felixfbecker** [comment]
Yey https://github.com/felixfbecker/php-language-server/pull/616/files
