### ISSUE TITLE
Merge all ini data to catch command-line ini settings

### ISSUE THREAD

**Issue by johnstevenson** [composer/xdebug-handler#29]
It is not possible to know if PHP is started with any `-d` ini value(s) so these will not be used for the restart. 

As a workaround (to fix specific Composer issues) xdebug-handler adds memory_limit, disable_functions and allow_url_fopen to the temporary ini file. I PR-ed a way of including all ini settings but there was concern about the extra time this adds to the restart: https://github.com/composer/composer/pull/6036

I have now set up a repo so that this can be tested on different set-ups: https://github.com/johnstevenson/xdebug-ini-test

Also included is a docker php image that uses a lot of ini files (58).  Its test results can be seen here: https://travis-ci.org/johnstevenson/xdebug-ini-test

In my view, the more robust method of merging all ini data adds a negligible amount of time to the restart and is a fix-and-forget solution. Feedback appreciated. @Seldaek I would be interested to see if you still see the "3-400ms" lag and how this is split up (between ini creation and start-up times).

**Comment by Seldaek** [comment]
Only have one ini file here, but it seems acceptable indeed. 100+ms for the restart kinda sucks though but I doubt we can do much there.

```
Simple Test
-----------

Inis read           :    1 ms (files: 1)
Process restarted   :  103 ms

Simple Test Merge
-----------------

Inis read/merged    :    4 ms (files: 1)
Process restarted   :  101 ms

Composer Test
-------------

xdebug-handler: The xdebug extension is loaded (2.6.0beta1)
xdebug-handler: Inis read:    1 ms (files: 1)
xdebug-handler: Process restarting (COMPOSER_ALLOW_XDEBUG=internal|2.6.0beta1|0)
xdebug-handler: Restarted (116 ms). The xdebug extension is not loaded
Composer version 1.7-dev (1b68adc7cf03b0c4adea3aee6efbc36fd6891f9e) 2018-01-05 17:55:59

Composer Test Merge
-------------------

xdebug-handler: The xdebug extension is loaded (2.6.0beta1)
xdebug-handler: Inis merged:  3 ms (files: 1)
xdebug-handler: Process restarting (COMPOSER_ALLOW_XDEBUG=internal|2.6.0beta1|0)
xdebug-handler: Restarted (140 ms). The xdebug extension is not loaded
Composer version 1.7-dev (1b68adc7cf03b0c4adea3aee6efbc36fd6891f9e) 2018-01-05 17:55:59
```

**Comment by johnstevenson** [comment]
> 100+ms for the restart kinda sucks

The restart interval obviously depends upon hardware capabilities and what the OS is doing at the time. The tests on Travis seem to be between 40-50ms (and generally take not much more time using the merge method: 0-10ms).

I did consider measuring how much longer it takes the restarted process to parse the additional (default) ini entries by hacking php to time it, but since you sound happy, I won't go to all that work.

**Comment by felixfbecker** [comment]
Could this be possible to disable with an option? In my use case I know `php` will never be launched with `-d`. If we have that option the impact wouldn't matter because everyone can choose whether they want it or not.

**Comment by johnstevenson** [comment]
@felixfbecker Yes, I guess we could (any suggestions? - a setter, in the constructor...). But from what I have seen, the difference seems to be negligible in terms of the overall restart time. Is this that important to you?

**Comment by felixfbecker** [comment]
I was just offering a solution to @Seldaek's concern. I would rather see us spend time on getting the absolute blockers in for a release and features like this can be added shortly after.

**Comment by Seldaek** [comment]
The 3ms of ini parsing are not a concern at all FWIW :) and changing that
won't solve my sluggish 100ms restart. I just need Lenovo to ship these new
thinkpads already..
