### ISSUE TITLE
Temporary ini file is not destroyed upon interruption

### ISSUE THREAD

**Issue by theofidry** [composer/xdebug-handler#50]
When using XdebugHandler, if the process is interrupted (before or after the restart), the temporary ini file created is kept. I don't think it's a big deal, it would be nicer if it would be properly removed.

**Comment by johnstevenson** [comment]
What exactly do you mean by interrupted - a crash, a signal, an extending class blocking something?

**Comment by theofidry** [comment]
I stopped the process with `ctrl + D` so signal in my case but I would expect the same for a crash

**Comment by johnstevenson** [comment]
Ah okay. I'm not aware that signals can be handled cross-platform.

**Comment by theofidry** [comment]
Indeed, looks like https://github.com/Seldaek/signal-handler does not work on Windows. That would help with Linux and OSX already though.

I have however mixed feelings about introducing this dependency to handle this edge case. I don't like the idea that you have temporary files around, but at the same time it's not critical either, so you're call

**Comment by johnstevenson** [comment]
I agree that it is not good to leave temporary stuff hanging around, but it is in the users tmp directory after all. I don't think it is a big deal.

**Comment by theofidry** [comment]
Alright, let's close this then :)

**Comment by Seldaek** [comment]
Sounds like this could probably  be handled in a __destruct handler or via register_shutdown_function. AFAIK those are run even on ctrl-C, or at least they'd be run in more cases than successful process completion.
