### ISSUE TITLE
Question of PHPRC

### ISSUE THREAD

**Issue by sanmai** [composer/xdebug-handler#60]
Why was it decided to use `-c` over `PHPRC`?

With the latter, the process is straightforward:

- Create our our php.ini with all other files merged it.
- Set `PHPRC` to point to *a directory* with our php.ini, set `PHP_INI_SCAN_DIR` to an empty string, with previous values saved somewhere.
- Run the original command as it is in `$argv` in the updated environment.
- Restore original  `PHPRC` and `PHP_INI_SCAN_DIR`.

No need to twiddle with command line options. No need for any workarounds. All other php invocations will a vanilla environment transparently. Hence, this is also backward compatible.

Using our xdebug-free environment for any of sub-processes is as simple as setting our custom values for `PHPRC` and `PHP_INI_SCAN_DIR`. This can be done from a callback like below, so a user won't even need to know the details:

```php
XdebugHandler::runWithoutXdebug(function () {
    $process = new Process();
    // and so on
});
```
`getRestartSettings()` and specifically `getRestartSettings()['tmpIni']` will became redundant with this approach. All complexity will be hidden from a user.

(I've already changed Infection's xdebug-handler to follow roughly this approach, with success, and I think this project can be made to adopt it too. Surely not without an owner's approval.)

**Comment by johnstevenson** [comment]
> Why was it decided to use -c over PHPRC?

Because `-c` takes precedence over all the other possible locations.

**Comment by sanmai** [comment]
Sure, and it makes it so much difficult to launch other processes without xdebug, don't you think?

**Comment by johnstevenson** [comment]
> Sure, and it makes it so much difficult to launch other processes without xdebug, don't you think?

I can't see how, unless I'm missing something here. In a restarted process you've got a "clean" environment (apart from the ini files issue) and access to the settings that were used in a restart. It is up to an application to decide what to do with them.

**Comment by sanmai** [comment]
Yes, that's correct. Let's say you want to run `vendor/bin/phpunit`, and it would want to run some PHP programs you have no control over, and you want *all of them* to exclude xdebug. Currently this is impossible.

But if xdebug-handler would use `PHPRC` to specify a path to php.ini, the feat above becomes possible.

**Comment by johnstevenson** [comment]
Of course it is possible. _You_ can use `PHPRC`. But it must be set to a file (otherwise the engine will scan for `php-cli.ini` in the entire search path, before searching the directory you specified).

- set `PHPRC` to the tmp ini
- set `PHP_INI_SCAN_DIR` to an empty string (if there were scanned inis)

Now your sub-process is in an xdebug-free environment and any child processes will safely use this environment.

> But if xdebug-handler would use PHPRC to specify a path to php.ini, the feat above becomes possible.

xdebug-handler has nothing to do with it (unless you are referring to my helper class, which could incorporate this pattern).

**Comment by sanmai** [comment]
That's my question. Would you mind if your helper class would incorporate this pattern?

**Comment by sanmai** [comment]
True it is better to set `PHPRC` directly to a file. 

(Path following logic [should generally find our file too](https://github.com/php/php-src/blob/543cab8a00f054bacd55633eeb312f7bbc1f5a21/main/php_ini.c#L455
), but it isn't as reliable. E.g. it can stumble upon php-cli.ini before our php.ini.)

**Comment by johnstevenson** [comment]
Ah, that makes more sense. Of course. Its purpose is to play around with patterns and ideas.

**Comment by sanmai** [comment]
I may not understand all correctly, but about what helper class we're talking? Would it be wrong if I would add this pattern right to `XdebugHandler`?

**Comment by johnstevenson** [comment]
>E.g. it can stumble upon php-cli.ini before our php.ini

That's what I said!

**Comment by johnstevenson** [comment]
The external helper class is mentioned in the readme. It is external while we experiment with stuff. https://github.com/johnstevenson/xdebug-handler-opts

It might or might not end up in the main repo, if there is a demand.

**Comment by sanmai** [comment]
I must confess I didn't dig that deep to know that one can set a path to a file in `PHPRC`. With that knowledge probably I can make Infection do what it should without a need to change XdebugHandler or anything. Thank you very much for giving me this eye-opener.

(Do you think it is a bad idea to mention this pattern in the README? It isn't very obvious.)

**Comment by johnstevenson** [comment]
No, it would be a good idea to mention it, but it is hard to write all this stuff clearly.

There is more than one way to skin a cat: for example using `-n` to suppress the additional ini scanning (which, incidentally, you wouldn't want because `PHPRC` would never be read) and which xdebug-handler does not currently use because there didn't seem much point in changing something that was already happily working. So I probably need to explain it all a bit better.

I will also update the helper class, so folks at least have some example code to look at (or use).

**Comment by sanmai** [comment]
Could you have a look at [this PR with workarounds we discussed here](https://github.com/infection/infection/pull/329) if you have a minute? Do these changes make any sense to you? Thanks in advance.

**Comment by borNfreee** [comment]
did you have a chance to look at that PR @johnstevenson ?

**Comment by sanmai** [comment]
@borNfreee I belive there's work underway in #67 to get our workarounds intergrated into XdebugHandler, but I don't think we should wait until XdebugHandler could do what we want; this will be a trivial thing to do later on.
