### ISSUE TITLE
Release process ?

### ISSUE THREAD

**Issue by keradus** [composer/xdebug-handler#71]
Hi !
Is there any release process that users can be aware about?

We have bunch of good changes already merged to master, but not released:
https://github.com/composer/xdebug-handler/compare/1.1.0...master

**Comment by johnstevenson** [comment]
No. I just haven't had a chance to finalize and release it. You are going to have to be patient.

**Comment by keradus** [comment]
I see, thanks for info ;)

**Comment by johnstevenson** [comment]
1.2.0 now [released](https://github.com/composer/xdebug-handler/releases/tag/1.2.0)

**Comment by keradus** [comment]
great to hear ! thanks for all your work, @johnstevenson ! really appreciating here !
