### ISSUE TITLE
Escaping of arguments strips-out non-ASCII characters.

### ISSUE THREAD

**Issue by dmromanov** [composer/xdebug-handler#74]
https://github.com/cakephp/debug_kit/issues/637
http://php.net/manual/en/function.escapeshellarg.php#99213

Description is comming soon...

**Comment by weirdan** [comment]
Basically `escapeshellarg()` is locale-dependent, and strips characters it does not expect to see according to current locale. Composer switches current locale to `C` to prevent another locale-related "bug" (lowercasing I when turkish locale is in effect).

**Comment by johnstevenson** [comment]
Thanks for the info, I'll fix this by not using `escapeshellarg`.
