### ISSUE TITLE
Restarted (child) process does not return color output (automatically)

### ISSUE THREAD

**Issue by k911** [composer/xdebug-handler#87]
Following #86. I've created small reproducer repository for those issues:
https://github.com/k911/composer-xdebug-handler-signals-bug-reproducer 

`Composer\XdebugHandler` does not detect properly (or at least automatically) TTY support in restarted process, which changes behaviour of CLI command.

### Reproducer file [colors.php](https://github.com/k911/composer-xdebug-handler-signals-bug-reproducer/blob/master/colors.php)

Requirements: `xdebug` and extension enabled

1. At first run command without restarting process

    ```bash
    ➜ APP_ALLOW_XDEBUG=1 php colors.php
    ```
    
    Output:

    ![color-output](https://github.com/k911/composer-xdebug-handler-signals-bug-reproducer/raw/master/img/color_output.png "Color Output")

   Which is expected.

2. Then, execute script without `APP_ALLOW_XDEBUG` environment variable

    ```bash
    ➜ php colors.php
    ```

    Output:
    
    ![no-color-output](https://github.com/k911/composer-xdebug-handler-signals-bug-reproducer/raw/master/img/no_color_output.png "No-Color Output")

I know, I still probably can force color output when using option like `--ansi` for some CLI tools, but in my opinion this should be detected automatically.

### Proposed solution
Use for example `symfony/process` which can detect it in one line:
https://github.com/k911/swoole-bundle/blob/0dc13f00b5604cbae4e20147bdbce04e4d98eb9d/src/Common/XdebugHandler/XdebugHandler.php#L74

**Comment by johnstevenson** [comment]
It is the responsibility of the library consumer to provide the `$colorOption` value. See: https://github.com/composer/xdebug-handler#coloroption

The library already handles whether the output is a tty. See: https://github.com/composer/xdebug-handler/blob/f8b834ad2da35e04dfa3076457837fb8c630868e/src/Process.php#L116

Just using an `isatty` function does not help if the end-user has provided a `no-color` param.
